version: '3.8'
services:
  supir-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /workspace/SUPIR-Installation/SUPIR:/workspace/SUPIR-Installation/SUPIR
      - /workspace/SUPIR-Installation/supir_jobs:/workspace/SUPIR-Installation/supir_jobs
    environment:
      - TOKEN=suP1R_Api-2025@Runpod#Xy7!Gp
    restart: always
